##
##  Makefile -- Build procedure for sample log_millisecond Apache module
##  Autogenerated via ``apxs -n log_millisecond -g''.
##

builddir=.
basedir=/usr/local/apache2
top_srcdir=$(basedir)
top_builddir=$(basedir)
include $(basedir)/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_log_millisecond.o mod_log_millisecond.lo mod_log_millisecond.slo mod_log_millisecond.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/log_millisecond

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

